// ─── Category Colors ───
export const CATEGORY_COLORS = {
  trigger:   '#7C3AED',
  data:      '#10B981',
  ai:        '#F97316',
  code:      '#06B6D4',
  merge:     '#3B82F6',
  output:    '#059669',
  scoring:   '#EC4899',
  gemini:    '#6366F1',
};

export const CATEGORY_LABELS = {
  trigger:  'TRIGGER',
  data:     'DATA SOURCE',
  ai:       'AI MODEL',
  code:     'CODE',
  merge:    'MERGE',
  output:   'OUTPUT',
  scoring:  'SCORING',
  gemini:   'GEMINI AI',
};

// ─── ALL 27 NODES (Aligned with Official Documentation) ───
export const WORKFLOW_NODES = [
  // ══════════ PIPELINE A — Student Engagement Scoring (11 nodes) ══════════
  {
    id: 'execute-workflow',
    name: 'Execute Workflow',
    subtitle: 'Manual Trigger',
    type: 'trigger',
    pipeline: 'A',
    what: 'Starts the entire 27-node pipeline with a single click. Simultaneously triggers all 4 data source reads (Student Data, Teacher Feedback, Teacher Notes, Teacher Transcript).',
    why: 'Acts as the single entry point for the entire system. One click processes everything — no need to run anything separately.',
    dataIn: 'Manual click or scheduled cron event',
    dataOut: 'Activation signal to all 4 data source nodes',
  },
  {
    id: 'student-data',
    name: 'Student Data',
    subtitle: 'Google Sheets — Read student form responses',
    type: 'data',
    pipeline: 'A',
    what: 'Reads all student feedback submissions from the Student Data Google Sheet. Each row is one student with 14 data columns: name, ID, email, understanding score, quiz percentage, interest level, doubt status, teaching pace, assignment score, open-ended feedback text, topic difficulty, and suggested improvement.',
    why: 'This is the primary data source. Everything the student self-reports about their classroom experience starts here.',
    dataIn: 'Google Sheet URL with student form responses',
    dataOut: 'Array of 10 student records, each with 14 fields',
  },
  {
    id: 'sentiment-conversion1',
    name: 'Sentiment Conversion1',
    subtitle: 'Groq LLM — Classify feedback sentiment',
    type: 'ai',
    pipeline: 'A',
    what: 'Sends each student\'s written feedback text to the Groq AI model. The AI reads the feedback and classifies the emotional tone as Positive, Neutral, or Negative. Runs once per student (10 API calls total).',
    why: 'Written feedback contains emotional signals that numbers alone cannot capture. A student might score 7/10 on understanding but write "I was totally lost" — the AI catches this mismatch.',
    dataIn: 'Student feedback text (e.g., "I understood most of the class but last part was confusing")',
    dataOut: 'JSON with student_id and feedback_level ("Positive" / "Neutral" / "Negative")',
    aiModel: 'Groq gpt-oss-120b',
  },
  {
    id: 'convert-sentiment',
    name: 'Convert Sentiment into Score',
    subtitle: 'Parse AI JSON response',
    type: 'code',
    pipeline: 'A',
    what: 'The AI returns a JSON string inside a text field. This JavaScript node parses that string, extracts the Student ID (which is used as the JSON key), and pulls out the feedback_level. Produces a clean flat object with student_id, student_name, and feedback_level.',
    why: 'AI responses are unpredictable in format. This node safely handles edge cases — if an AI response is malformed or empty, it skips silently instead of crashing the pipeline.',
    dataIn: 'Raw AI text response (JSON string)',
    dataOut: 'Clean object: { student_id: "101", student_name: "Dhruv", feedback_level: "Neutral" }',
  },
  {
    id: 'teacher-feedback',
    name: 'Teacher Feedback',
    subtitle: 'Google Sheets — Read teacher evaluations',
    type: 'data',
    pipeline: 'A',
    what: 'Reads the teacher\'s behavioral evaluation for each student from a separate Google Sheet. Contains 6 columns: Student ID, Teacher Participation (1-10), Teacher Attention (1-10), Teacher Understanding (1-10), Effort (1-10), and Teacher Remark (free text).',
    why: 'Adds an objective layer that student self-assessment cannot provide. A student might rate themselves high, but the teacher\'s observation may tell a different story.',
    dataIn: 'Google Sheet URL with teacher feedback',
    dataOut: 'Array of 10 teacher evaluation records',
  },
  {
    id: 'combine-conversion',
    name: 'Combine Conversion',
    subtitle: '3-source data merge using Student ID',
    type: 'code',
    pipeline: 'A',
    what: 'The most critical node in the pipeline. Pulls data from three separate sources — Student Data, Sentiment Results, and Teacher Feedback — and merges them into a single unified record per student using Student ID as the join key.',
    why: 'This is where isolated data becomes a complete picture. Without this merge, student self-reports, AI analysis, and teacher observations would remain in separate silos.',
    dataIn: '3 arrays from 3 different nodes',
    dataOut: 'Single JSON containing all 10 students, each with all fields from all 3 sources combined',
  },
  {
    id: 'code-js1',
    name: 'Code in JavaScript1',
    subtitle: 'Split merged array into individual rows',
    type: 'code',
    pipeline: 'A',
    what: 'The Combine Conversion node outputs ONE item containing all 10 students in a single array. This node splits that array into 10 individual items so each student becomes its own data row for the next nodes.',
    why: 'Google Sheets Append needs individual items, not a single array. This structural transformation is required for proper row-by-row writing.',
    dataIn: 'Single JSON with students array',
    dataOut: '10 separate items, one per student',
  },
  {
    id: 'append-row',
    name: 'Append Row in Sheet',
    subtitle: 'Write merged data to Combine Data sheet',
    type: 'output',
    pipeline: 'A',
    what: 'Takes each student\'s merged record (student data + teacher feedback + sentiment) and appends it as a row in the Combine Data Google Sheet. Maps 19 columns including all student fields, teacher metrics, and feedback sentiment.',
    why: 'Creates a permanent combined dataset that serves as the foundation for score calculation. This sheet contains the complete picture before scoring.',
    dataIn: 'Individual student records with all merged fields',
    dataOut: 'Rows written to Google Sheets',
  },
  {
    id: 'engagement-score',
    name: 'Engagement Score & Risk',
    subtitle: 'Weighted formula — Calculate final score and risk level',
    type: 'scoring',
    pipeline: 'A',
    what: 'Applies the three-part weighted engagement formula to each student. Calculates Student Score (from understanding, quiz, interest, assignment, doubt, pace), Teacher Score (from participation, attention, understanding, effort), and combines them with the AI sentiment score to produce the Final Engagement Score. Classifies students as Low Risk (≥75), Medium Risk (50-74), or High Risk (<50).',
    why: 'This is the core algorithm of EduPulse. It transforms 20+ raw data points into a single actionable number and risk classification.',
    dataIn: 'Student records with all metrics',
    dataOut: 'Same records with 4 new fields: Student Score, Teacher Score, Final Engagement Score, Risk',
    formula: 'Final = 0.6 × Student Score + 0.3 × Teacher Score + 0.1 × Feedback Score',
  },
  {
    id: 'engagement-data',
    name: 'Engagement Score and Risk Data',
    subtitle: 'Write final scores to output Google Sheet',
    type: 'output',
    pipeline: 'A',
    what: 'Writes the fully scored student data (including Final Engagement Score and Risk Level) to the output Google Sheet. Uses AppendOrUpdate mode with Student ID as the match key, so running the workflow again updates existing students instead of creating duplicates.',
    why: 'This is the sheet connected to the SheetDB API that powers the live dashboard at foai-4iif.vercel.app. Whatever is written here appears on the website.',
    dataIn: 'Scored student records',
    dataOut: 'Updated Google Sheet → SheetDB API → Dashboard',
  },
  {
    id: 'code-js2',
    name: 'Code in JavaScript2',
    subtitle: 'Transform student data for class analytics',
    type: 'code',
    pipeline: 'A',
    what: 'Takes the scored student data from the Engagement Score sheet and transforms it into a clean, normalized format optimized for AI analysis. Converts doubt levels to HIGH/MEDIUM/LOW, uppercases pace and difficulty values, restructures teacher metrics into a nested object.',
    why: 'The class analytics AI model (Gemini) works better with consistently formatted, clean data. This transformation ensures optimal analysis quality.',
    dataIn: 'Raw scored student records',
    dataOut: 'Normalized student data objects',
  },

  // ══════════ PIPELINE B — Teacher Transcript Analysis (11 nodes) ══════════
  {
    id: 'teacher-notes',
    name: 'Teacher Notes',
    subtitle: 'Google Docs — Read syllabus notes',
    type: 'data',
    pipeline: 'B',
    what: 'Fetches the official syllabus notes document from Google Docs. This document contains all topics, subtopics, formulas, examples, and concepts that the teacher is expected to cover in the lecture.',
    why: 'This is the reference standard. The AI uses this to determine what SHOULD have been taught.',
    dataIn: 'Google Docs URL',
    dataOut: 'Full document text (can be 5,000-15,000+ characters)',
  },
  {
    id: 'teacher-transcript',
    name: 'Teacher Transcript',
    subtitle: 'Google Docs — Read lecture transcript',
    type: 'data',
    pipeline: 'B',
    what: 'Fetches the full text transcript of what the teacher actually said during the lecture from Google Docs.',
    why: 'This is compared against the syllabus notes to determine how much of the required content was actually covered in class.',
    dataIn: 'Google Docs URL',
    dataOut: 'Full transcript text (can be 5,000-15,000+ characters)',
  },
  {
    id: 'chunk-notes',
    name: 'Chunk Notes',
    subtitle: 'Smart extraction — Reduce token usage by 70%',
    type: 'code',
    pipeline: 'B',
    what: 'Takes the full syllabus notes document and extracts key sections to reduce its size for the AI model. Extracts the first 1,500 characters (introduction and early topics), 4 key sentences from evenly-spaced positions in the middle, and the last 1,500 characters (final topics). Documents under 3,000 characters pass through unchanged.',
    why: 'Full documents can be 10,000+ characters, which consumes excessive API tokens and may exceed model limits. This chunking reduces input by approximately 70% while preserving content from every section.',
    dataIn: 'Full document text (~10,000+ characters)',
    dataOut: 'Chunked summary (~3,500 characters)',
  },
  {
    id: 'chunk-transcript',
    name: 'Chunk Transcript',
    subtitle: 'Smart extraction — Same chunking for transcript',
    type: 'code',
    pipeline: 'B',
    what: 'Applies the identical chunking logic to the lecture transcript. First 1,500 characters + 4 middle sentences + last 1,500 characters.',
    why: 'Both documents must be chunked for a fair comparison. If only one were chunked, the AI comparison would be unbalanced.',
    dataIn: 'Full transcript text',
    dataOut: 'Chunked transcript summary',
  },
  {
    id: 'merge',
    name: 'Merge',
    subtitle: 'Combine chunked notes + chunked transcript',
    type: 'merge',
    pipeline: 'B',
    what: 'Takes the chunked syllabus notes and the chunked transcript and combines them into a single data object so the AI can access both in one prompt.',
    why: 'The AI comparison node needs both documents in the same input. This merge ensures they arrive together.',
    dataIn: 'Two separate chunked documents',
    dataOut: 'Single object with notes_summary and transcript_summary fields',
  },
  {
    id: 'basic-llm',
    name: 'Basic LLM Chain',
    subtitle: 'Groq AI — Compare transcript vs syllabus',
    type: 'ai',
    pipeline: 'B',
    what: 'Sends both the chunked notes and chunked transcript to Groq AI with a comparison prompt. The AI identifies which syllabus topics were covered, which were missed, which were partially covered, estimates off-topic time, calculates an overall match percentage (0-100), and assigns a rating (EXCELLENT / GOOD / POOR / FAIL).',
    why: 'This is the core of the teacher analysis system. It answers: "Did the teacher actually teach what they were supposed to teach?"',
    dataIn: 'Merged notes + transcript',
    dataOut: 'JSON with covered_topics, missed_topics, partially_covered_topics, match_percentage, rating',
  },
  {
    id: 'code-js-b',
    name: 'Code in JavaScript',
    subtitle: 'Parse and normalize AI coverage analysis',
    type: 'code',
    pipeline: 'B',
    what: 'Parses the raw JSON text returned by the AI and normalizes it into a clean structure. Handles variations in the AI response format (the AI might use "covered" or "covered_topics" as key names). Safely extracts topic arrays, parses off-topic time from strings, and handles missing or malformed fields.',
    why: 'AI responses are not always consistent in structure. This node acts as a safety layer that ensures downstream nodes always receive clean, predictable data.',
    dataIn: 'Raw AI JSON response',
    dataOut: 'Clean object with covered, missed, partial arrays, off_topic_time, match_percentage, rating',
  },
  {
    id: 'code-js3',
    name: 'Code in JavaScript3',
    subtitle: 'Aggregate and deduplicate results',
    type: 'code',
    pipeline: 'B',
    what: 'Aggregates the parsed results using JavaScript Sets (to prevent duplicate topic names), sums off-topic time, averages match percentages, and determines the final rating using priority logic (POOR overrides GOOD).',
    why: 'Ensures the final teacher analysis is clean and deduplicated before being sent for summarization.',
    dataIn: 'Parsed coverage data',
    dataOut: 'Aggregated coverage summary',
  },
  {
    id: 'basic-llm1',
    name: 'Basic LLM Chain1',
    subtitle: 'Groq AI — Generate teacher performance summary',
    type: 'ai',
    pipeline: 'B',
    what: 'Takes the structured coverage analysis and generates a concise teacher performance summary in JSON format. Includes coverage_score, topics_covered, topics_missed, topics_partial, off_topic_minutes, overall_rating, key_strengths, areas_for_improvement, and a 2-3 sentence summary.',
    why: 'Transforms raw data into a human-readable teacher evaluation that can be included in the final report.',
    dataIn: 'Structured coverage data',
    dataOut: 'Teacher performance summary JSON',
  },

  {
    id: 'groq-chat-model-1',
    name: 'Groq Chat Model',
    subtitle: 'LLM Model — llama-3.1-8b',
    type: 'ai',
    pipeline: 'B',
    what: 'The actual inference engine for transcript comparison. Provides the brain for the LLM Comparison node.',
    why: 'Separating the model from the chain allows for easy switching of AI providers (Groq/OpenAI/Anthropic) without changing the logic.',
    dataIn: 'Prompt from LLM Comparison',
    dataOut: 'Raw text generation',
    aiModel: 'Groq llama-3.1-8b-instant',
  },
  {
    id: 'groq-chat-model-2',
    name: 'Groq Chat Model',
    subtitle: 'LLM Model — llama-3.1-8b',
    type: 'ai',
    pipeline: 'B',
    what: 'The inference engine for generating the teacher performance summary.',
    why: 'Ensures consistent summarization quality across all reports.',
    dataIn: 'Prompt from Teacher Summary',
    dataOut: 'Raw text generation',
    aiModel: 'Groq llama-3.1-8b-instant',
  },

  // ══════════ PIPELINE C — Report Generation (5 nodes) ══════════
  {
    id: 'message-model',
    name: 'Message a Model',
    subtitle: 'Google Gemini 2.0 Flash — Class-level analytics',
    type: 'gemini',
    pipeline: 'C',
    what: 'Analyzes ALL student data together to produce class-level insights. Determines total students, risk distribution (how many low/medium/high), average scores (understanding, quiz, engagement), top issues across the class (e.g., "fast pace", "many doubts"), common patterns, and overall class status (STRONG / AVERAGE / WEAK).',
    why: 'Individual scores are useful, but class-level patterns reveal systemic issues. If 60% of students report "Fast" pace, the problem is the teaching speed, not the students.',
    dataIn: 'All 10 normalized student records',
    dataOut: 'Class analysis JSON with risk_distribution, average_scores, top_issues, common_patterns, class_status',
  },
  {
    id: 'merge1',
    name: 'Merge1',
    subtitle: 'Combine student analytics + teacher analysis',
    type: 'merge',
    pipeline: 'C',
    what: 'Merges two data streams: the class-level student analytics (from Gemini) and the teacher performance analysis (from Groq). Creates a single combined data package for the final report.',
    why: 'The final report needs both perspectives — how students are performing AND how well the teacher is teaching. This merge brings both halves together.',
    dataIn: 'Student analytics JSON + Teacher performance JSON',
    dataOut: 'Combined analysis package',
  },
  {
    id: 'message-model1',
    name: 'Message a Model1',
    subtitle: 'Google Gemini 2.0 Flash — Generate final report',
    type: 'gemini',
    pipeline: 'C',
    what: 'Takes the combined student + teacher analysis and generates a comprehensive text report with 4 sections: Class Overview (total students, status, risk distribution), Student Performance (average scores, top issues, patterns), Teacher Performance (coverage score, topics covered vs missed, strengths, improvements), and Recommendations (top 3 actionable steps).',
    why: 'This is the final deliverable — a professional, readable report that a principal or administrator could use to understand classroom engagement at a glance.',
    dataIn: 'Combined analysis JSON',
    dataOut: 'Structured text report (max 500 words)',
  },
  {
    id: 'update-doc',
    name: 'Update a Document',
    subtitle: 'Write report to Google Docs',
    type: 'output',
    pipeline: 'C',
    what: 'Takes the generated report text and inserts it into a Google Doc for permanent storage and sharing. Handles both Gemini response format (candidates[0].content.parts[0].text) and Groq format (text field) dynamically.',
    why: 'The report needs to live somewhere permanent and shareable. A Google Doc can be shared with administrators, printed for meetings, or referenced later.',
    dataIn: 'Generated report text',
    dataOut: 'Updated Google Doc',
  },
  {
    id: 'gemini-model',
    name: 'Gemini 2.0 Flash',
    subtitle: 'AI Model Engine',
    type: 'gemini',
    pipeline: 'C',
    what: 'The high-intelligence model engine powering both class analytics and final report generation.',
    why: 'Gemini 2.0 Flash provides the long-context window needed to process all 10 students and teacher analysis simultaneously.',
    dataIn: 'Prompt from Class Analysis / Report Generator',
    dataOut: 'Advanced reasoning & text generation',
  },
];

// ─── CONNECTIONS ───
// Each entry: [fromId, toId]
export const WORKFLOW_CONNECTIONS = [
  // Pipeline A
  ['execute-workflow', 'student-data'],
  ['execute-workflow', 'teacher-feedback'],
  ['student-data', 'sentiment-conversion1'],
  ['sentiment-conversion1', 'convert-sentiment'],
  ['convert-sentiment', 'combine-conversion'],
  ['teacher-feedback', 'combine-conversion'],
  ['combine-conversion', 'code-js1'],
  ['code-js1', 'append-row'],
  ['append-row', 'engagement-score'],
  ['engagement-score', 'engagement-data'],
  ['engagement-data', 'code-js2'],

  // Pipeline B
  ['execute-workflow', 'teacher-notes'],
  ['execute-workflow', 'teacher-transcript'],
  ['teacher-notes', 'chunk-notes'],
  ['teacher-transcript', 'chunk-transcript'],
  ['chunk-notes', 'merge'],
  ['chunk-transcript', 'merge'],
  ['merge', 'basic-llm'],
  ['basic-llm', 'groq-chat-model-1'],
  ['basic-llm1', 'groq-chat-model-2'],
  ['code-js-b', 'code-js3'],
  ['code-js3', 'basic-llm1'],

  // Pipeline C (cross-pipeline connections)
  ['code-js2', 'message-model'],
  ['message-model', 'merge1'],
  ['message-model', 'gemini-model'],
  ['message-model1', 'gemini-model'],
  ['basic-llm1', 'merge1'],
  ['merge1', 'message-model1'],
  ['message-model1', 'update-doc'],
];
