export const WORKFLOW_NODES = [
  {
    id: 'trigger',
    name: 'Execute Workflow',
    icon: '▶️',
    type: 'trigger',
    x: 50, y: 300,
    what: 'Initiates the entire data processing pipeline when triggered manually or on a schedule.',
    why: 'Acts as the starting point — nothing runs without this trigger. It ensures data is processed at the right time.',
    dataIn: 'Manual click or scheduled cron event',
    dataOut: 'Activation signal',
  },
  {
    id: 'student-data',
    name: 'Student Data (Google Sheet)',
    icon: '📊',
    type: 'data',
    x: 250, y: 150,
    what: 'Reads raw student form submissions from the Google Sheet connected via Google Sheets API.',
    why: 'Google Sheets is the primary database where all student form responses land after submission.',
    dataIn: 'Google Sheet URL / API Key',
    dataOut: 'Array of student records',
  },
  {
    id: 'teacher-feedback',
    name: 'Teacher Feedback (Sheet)',
    icon: '👨‍🏫',
    type: 'data',
    x: 250, y: 450,
    what: 'Reads teacher evaluations and observations for each student from a separate sheet tab.',
    why: 'Student self-assessment alone is incomplete. Teacher perspective adds accuracy.',
    dataIn: 'Teacher evaluations sheet',
    dataOut: 'Teacher feedback records',
  },
  {
    id: 'sentiment-ai',
    name: 'Sentiment Conversion (AI)',
    icon: '🧠',
    type: 'ai',
    x: 500, y: 150,
    what: 'Sends each student\'s written feedback to an AI model that classifies the tone.',
    why: 'Written feedback contains emotional signals that numbers alone cannot capture.',
    dataIn: 'Raw feedback text',
    dataOut: 'Sentiment label (Pos/Neu/Neg)',
  },
  {
    id: 'groq-model',
    name: 'Groq Chat Model',
    icon: '⚡',
    type: 'ai',
    x: 500, y: 300,
    what: 'The actual AI language model (hosted by Groq) that processes the analysis.',
    why: 'Groq provides extremely fast inference speeds, making real-time analysis possible.',
    dataIn: 'Prompt + feedback text',
    dataOut: 'AI-generated sentiment',
  },
  {
    id: 'convert-sentiment',
    name: 'Convert Sentiment to Score',
    icon: '🔢',
    type: 'code',
    x: 750, y: 150,
    what: 'Converts the text sentiment label into a numeric score (100, 50, or 0).',
    why: 'The engagement formula needs numbers, not text.',
    dataIn: 'Sentiment label',
    dataOut: 'Numeric sentiment score',
  },
  {
    id: 'combine',
    name: 'Combine Data',
    icon: '🔗',
    type: 'code',
    x: 750, y: 400,
    what: 'Merges student data, teacher feedback, and the sentiment score into one record.',
    why: 'All data sources must be joined before final calculation.',
    dataIn: 'Student + Teacher + AI data',
    dataOut: 'Unified student record',
  },
  {
    id: 'code-js',
    name: 'Score Calculation (JS)',
    icon: '💻',
    type: 'code',
    x: 1000, y: 400,
    what: 'Runs a custom JS function that calculates the Final Engagement Score.',
    why: 'The score uses a carefully designed formula that weighs different factors.',
    dataIn: 'Combined numeric fields',
    dataOut: 'Final Engagement Score (0-100)',
  },
  {
    id: 'append-sheet',
    name: 'Update Results Sheet',
    icon: '📝',
    type: 'output',
    x: 1250, y: 400,
    what: 'Writes the fully processed student record back to the output Google Sheet.',
    why: 'Stores results for the dashboard to read via SheetDB API.',
    dataIn: 'Complete processed record',
    dataOut: 'Updated Google Sheet',
  },
  {
    id: 'risk-calc',
    name: 'Engagement Score Risk',
    icon: '⚠️',
    type: 'code',
    x: 1250, y: 200,
    what: 'Evaluates the score and assigns a risk category based on thresholds.',
    why: 'Helps teachers instantly identify which students need the most attention.',
    dataIn: 'Engagement Score',
    dataOut: 'Risk label (Low/Med/High)',
  },
  {
    id: 'final-output',
    name: 'Final Dashboard Data',
    icon: '✅',
    type: 'output',
    x: 1450, y: 300,
    what: 'The final output sheet that powers the student and teacher dashboards.',
    why: 'This is the single source of truth for the entire EduPulse platform.',
    dataIn: 'Final Scores + Risk Levels',
    dataOut: 'Live Dashboard Data',
  },
];

export const WORKFLOW_CONNECTIONS = [
  ['trigger', 'student-data'],
  ['trigger', 'teacher-feedback'],
  ['student-data', 'sentiment-ai'],
  ['sentiment-ai', 'groq-model'],
  ['groq-model', 'sentiment-ai'],
  ['sentiment-ai', 'convert-sentiment'],
  ['convert-sentiment', 'combine'],
  ['teacher-feedback', 'combine'],
  ['combine', 'code-js'],
  ['code-js', 'append-sheet'],
  ['append-sheet', 'risk-calc'],
  ['risk-calc', 'final-output'],
];
